NumPy(Numerical Python)
- 고성능 과학 계산용 패키치, 강력한 N차원 배열 객체
- 데이터 처리에 사용 가능한 다차원 컨테이너
- 정교한 브로드캐스팅(broadcasting)기능
- 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
- 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
- 데이터 과학 도구의 핵심 ( Numpy 패키지를 활용한 다양한 패키지 존재)

In [2]:
import numpy as np

# 배열 생성 / 초기화

## 리스트로 생성

In [8]:
a1 = np.array([1,2,3,4,5]) # 1D array
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4]) # list와 같이 idx로 접근가능.
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [12]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2D array
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [16]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]]) # 3D array
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


## 배열 생성 및 초기화

- zeros() : 모든 element를 0으로 초기화

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones() : 모든 element를 1로 초기화

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((3,3)) #다 차원도 가능

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full() : 모든 element를 지정한 값으로 초기화 / 정수,실수 전부가능

In [21]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye() : Identity(단위 행렬) 생성 , 단위행렬은 정방 행렬이기 때문에 shape가 아닌 dim 입력

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- tri() : 삼각행렬 생성

In [23]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty() : 초기화되지 않은 배열 생성(초기화가 없어서 배열 생성 빠름, 기존 메모리 위치에 존재하는 값이 있음

In [24]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- _like() : 지정된 배열과 shape가 같은 행렬 생성

In [25]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [26]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

## 생성한 값으로 배열 생성

- arange() : 정수 범위로 배열 생성

In [31]:
np.arange(0,30,2)    # (start, < stop,step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace() : 범위내에서 균등 간격의 배열 생성

In [33]:
np.linspace(0,1,5) # 0 ~ 1 까지를 균등하게 5개로 나눔.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace() : 범위내에서 균등간격으로 로그 스케일 배열 생성

In [34]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

## 랜덤값으로 배열 생성

- random.random():랜덤한 수의 배열 생성 (실수값 반환)

In [35]:
np.random.random((3,3))

array([[0.20065721, 0.16667834, 0.86992363],
       [0.99154415, 0.79982087, 0.80252247],
       [0.84435456, 0.58628662, 0.37214249]])

- random.randint() : 일정 구간의 랜덤 정수의 배열 생성

In [37]:
np.random.randint(0,10,(3,3))  #(range,range,(shape))

array([[7, 6, 7],
       [4, 4, 6],
       [1, 0, 0]])

- random.normal(): Normal Distribution를 고려한 랜덤한 수의 배열 생성

In [39]:
np.random.normal(0,1,(3,3))  # (평균, 표준편차, (사이즈))

array([[-0.49741766,  0.24702499,  0.49878718],
       [-1.17774629,  0.66039217,  0.57064354],
       [-0.15351716, -2.43728005,  0.53485458]])

- random.rand() : Uniform Distribution을 고려한 랜덤한 수의 배열 생성

In [40]:
np.random.rand(3,3)

array([[0.46174036, 0.52530707, 0.56236858],
       [0.97822469, 0.85980625, 0.91929192],
       [0.49745877, 0.90776206, 0.97843033]])

- random.randn() : Standard Normal Distribution을 고려한 랜덤한 수의 배열 생성

In [41]:
np.random.randn(3,3)

array([[ 0.70586519, -0.78926487,  1.28233638],
       [ 1.24450453,  0.94716892, -0.09864589],
       [ 0.46533662, -0.41265553,  0.05789723]])

## 표준 데이터 타입

In [43]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 날짜/시간 배열 생성

In [47]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [48]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [49]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [51]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

# 배열 조회

## 배열 속성 정보

In [52]:
def array_info(array):
    print(array)
    print("ndim:",array.ndim)
    print("shape:",array.shape)
    print("dtype:",array.dtype)
    print("size:", array.size)
    print("itemsize:",array.itemsize)
    print("nbytes:",array.nbytes)
    print("strides:",array.strides)

In [53]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [54]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [55]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


## 인덱싱(Indexing)

In [57]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
5
5
4


In [58]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [59]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


## 슬라이싱(Slicing)

- a[start:stop:step]  start <= ~ < stop
- 기본값 : start = 0, stop = ndim, step = 1

In [60]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [61]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱(Boolean Indexing)
- 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
- True 값인 인덱스의 값만 조회

In [64]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True,False,True,True,False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [66]:
print(a2)
bi = np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
[1 2 3 4 6 7 8 9]


## 팬시 인덱싱(Fancy Indexing)

In [69]:
print(a1)
print([a1[0],a1[2]])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1],       # Fancy Indexing의 결과 dim은 index의 dim을 따라감
                [2,0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [72]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])
print(a2[row,1])
print(a2[2,col])
print(a2[row,1:])
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


# 배열 값 삽입/수정/삭제/복사

## 배열 값 삽입
- insert() : 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [77]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [78]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


## 배열 값 수정
- 배열의 인덱싱으로 접근하여 값 수정

In [87]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9 # 슬라이싱에 포함된 모든 원소를 변경
print(a1) 
i = np.array([1,3,4])
a1[i] = 0 # fancy indexing
print(a1) 
a1[i] += 4 # 증감 연산자 사용가능
print(a1)

[9 4 3 4 4]
[1 2 3 4 4]
[9 2 3 4 4]
[9 0 3 0 0]
[9 4 3 4 4]


In [92]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1 # 전체 ROW 변경
print(a2)
a2[1:,2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


## 배열 값 삭제
- delete() : 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [93]:
print(a1)
b1 = np.delete(a1,1)
print(b1)

[9 4 3 4 4]
[9 3 4 4]


In [95]:
print(a2)
b2 = np.delete(a2,1,axis=0)
print(b2)
c2 = np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


## 배열 복사
- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [99]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0  ## 원본 배열도 변경되어 버림
print(a2_sub) 
print(a2) 

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


- copy() : 배열이나 하위 배열 내의 값을 명시적으로 복사

In [101]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


# 배열 변환

## 배열 전치 및 축 변경

In [102]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [103]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [104]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [105]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


## 배열 재구조화

- reshape() : 배열의 형상을 변경

In [107]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis() : 새로운 축 추가

In [108]:
print(n1)
print(n1[np.newaxis, :5]) # 행방향
print(n1[:5, np.newaxis]) # 열방향, 즉 차원 방향으로

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 배열 크기 변경

- 배열 모양만 변경

In [111]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[1 2 1 3 0]
 [8 9 8 6 2]]
[[1 2]
 [1 3]
 [0 8]
 [9 8]
 [6 2]]


- 배열 크기 증가, 남은 공간 0으로 채워짐

In [113]:
n2.resize((5,5))
print(n2)

[[1 2 1 3 0]
 [8 9 8 6 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 삭제

In [114]:
n2.resize((3,3))
print(n2)

[[1 2 1]
 [3 0 8]
 [9 8 6]]


## 배열 추가

- append() : 배열의 끝에 값 추가

In [117]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [118]:
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis = 0으로 지정 shape[0]을 제외한 나머지 shape 같아야함.

In [119]:
c2 = np.append(a2,b2,axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis = 1으로 지정 shape[1]을 제외한 나머지 shape 같아야함.

In [120]:
c2 = np.append(a2,b2,axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 배열 연결

- concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 배열 연경

In [123]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [124]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [125]:
a2 = np.array([[1,2,3],[4,5,6]]) 
np.concatenate([a2,a2])  # axis는 기본으로 0으로 지정

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [126]:
a2 = np.array([[1,2,3],[4,5,6]]) 
np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- vstack() : vertical stack, 1차원으로 연결

In [127]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack(): horizontal stack, 2차원으로 연결

In [129]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack(): depth stack, 3차원으로 연결

In [130]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack() : 새로운 차원으로 연결

In [131]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## 배열 분할

- split() : 배열 분할

In [133]:
a1 = np.arange(0,10)
print(a1)
b1,c1 = np.split(a1,[5])
print(b1,c1)
b1, c1, d1,e1,f1 =np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


- vsplit() : 수직분할, 1차원 분할

In [134]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- hsplit() : 수평 분할, 2차원으로 분할

In [135]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- dsplit():깊이분할, 3차원으로 분할

In [136]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


# 배열 연산
- NumPy의 배열 연산은 벡터화(vectorized)연산을  사용
- 일반적으로 NumPy의 범용 함수(universal functions)을 통해 구현
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행

## 브로드캐스팅(Broadcasting)

In [139]:
a1 = np.array([1,2,3])
print(a1)
print(a1 + 5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1 + a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술연산

In [147]:
a1 = np.arange(1,10)
print(a1)
print(a1 + 1)
print(np.add(a1,10))
print(a1 - 2)
print(np.subtract(a1,10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1,2))
print(a1 / 2)
print(np.divide(a1,2))
print(a1 // 2)
print(np.floor_divide(a1,2))
print(a1 ** 2)
print(np.power(a1,2))
print(a1 % 2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [149]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[5 7 5 1 7 1 8 8 9]
[ 6  9  8  5 12  7 15 16 18]
[-4 -5 -2  3 -2  5 -1  0  0]
[ 5 14 15  4 35  6 56 64 81]
[0.2        0.28571429 0.6        4.         0.71428571 6.
 0.875      1.         1.        ]
[0 0 0 4 0 6 0 1 1]
[        1       128       243         4     78125         6   5764801
  16777216 387420489]
[1 2 3 0 5 0 7 0 0]


In [151]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [2 8 2]
 [4 3 7]]
[[ 8  6  4]
 [ 6 13  8]
 [11 11 16]]
[[-6 -2  2]
 [ 2 -3  4]
 [ 3  5  2]]
[[ 7  8  3]
 [ 8 40 12]
 [28 24 63]]
[[0.14285714 0.5        3.        ]
 [2.         0.625      3.        ]
 [1.75       2.66666667 1.28571429]]
[[0 0 3]
 [2 0 3]
 [1 2 1]]
[[      1      16       3]
 [     16  390625      36]
 [   2401     512 4782969]]
[[1 2 0]
 [0 5 0]
 [3 2 2]]


### 절대값 함수(Absolute Function)

- absolute(), abs() : 내장 절대값 함수

In [154]:
a1 = np.random.randint(-10,10,5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 4 -3 -5  8 -8]
[4 3 5 8 8]
[4 3 5 8 8]


### 제곱/제곱근 함수

- square,sqrt: 제곱, 제곱근함수

In [157]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 4 -3 -5  8 -8]
[16  9 25 64 64]
[2.                nan        nan 2.82842712        nan]


/var/folders/td/4qb43vgx4w92xyck7j2hlgph0000gn/T/ipykernel_44551/2033102379.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


### 지수와 로그 함수(Exponential and Log Function)

In [158]:
a1 = np.random.randint(1,10,5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[7 4 4 4 1]
[1096.63315843   54.59815003   54.59815003   54.59815003    2.71828183]
[128.  16.  16.  16.   2.]
[49 16 16 16  1]


In [159]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 4 4 4 1]
[1.94591015 1.38629436 1.38629436 1.38629436 0.        ]
[2.80735492 2.         2.         2.         0.        ]
[0.84509804 0.60205999 0.60205999 0.60205999 0.        ]


### 삼각함수(Trigonometrical Function)

In [163]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [164]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계함수

#### sum():합계산

In [169]:
a2 = np.random.randint(1,10,(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
41 41
[11 20 10] [11 20 10]
[12 17 12] [12 17 12]


#### cumsum():누적합 계산

In [171]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
[ 2 10 12 19 22 29 31 40 41]
[[ 2  8  2]
 [ 9 11  9]
 [11 20 10]]
[[ 2 10 12]
 [ 7 10 17]
 [ 2 11 12]]


#### diff():차분 계산

In [172]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
[[ 6 -6]
 [-4  4]
 [ 7 -8]]
[[ 5 -5  5]
 [-5  6 -6]]
[[ 6 -6]
 [-4  4]
 [ 7 -8]]


#### prod():곱 계산

In [173]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
84672
[ 28 216  14]
[ 32 147  18]


#### comprod():누적곱 계산

In [174]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
[    2    16    32   224   672  4704  9408 84672 84672]
[[  2   8   2]
 [ 14  24  14]
 [ 28 216  14]]
[[  2  16  32]
 [  7  21 147]
 [  2  18  18]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [175]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [17 17 17]
 [12 12 12]]
[[12 12 12]
 [17 17 17]
 [12 12 12]]


#### tensordot():텐서곱 계산

In [176]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
41
[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
[[12 12 12]
 [17 17 17]
 [12 12 12]]


#### cross(): 벡터곱

In [177]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner()/outer(): 벡터 내적/외적

In [178]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [17 17 17]
 [12 12 12]]
[[2 2 2 2 2 2 2 2 2]
 [8 8 8 8 8 8 8 8 8]
 [2 2 2 2 2 2 2 2 2]
 [7 7 7 7 7 7 7 7 7]
 [3 3 3 3 3 3 3 3 3]
 [7 7 7 7 7 7 7 7 7]
 [2 2 2 2 2 2 2 2 2]
 [9 9 9 9 9 9 9 9 9]
 [1 1 1 1 1 1 1 1 1]]


#### mean():평균 계산

In [179]:
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
4.555555555555555
[3.66666667 6.66666667 3.33333333]
[4.         5.66666667 4.        ]


#### std():표준 편차 계산

In [180]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
2.9481109247603556
[2.3570226  2.62466929 2.62466929]
[2.82842712 1.88561808 3.55902608]


#### var():분산 계산

In [182]:
print(a2)
print(np.var(a2))
print(np.var(a2,axis=0))
print(np.var(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
8.69135802469136
[5.55555556 6.88888889 6.88888889]
[ 8.          3.55555556 12.66666667]


#### min():최소값

In [183]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
1
[2 3 1]
[2 3 1]


#### max():최대값

In [184]:
print(a2)
print(np.max(a2))
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
9
[7 9 7]
[8 7 9]


#### argmin():최소값 인덱스

In [185]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2,axis=0))
print(np.argmin(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
8
[0 1 2]
[0 1 2]


#### argmax():최대값 인덱스

In [186]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
7
[1 2 1]
[1 0 1]


#### median():중앙값

In [187]:
print(a2)
print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))

[[2 8 2]
 [7 3 7]
 [2 9 1]]
3.0
[2. 8. 2.]
[2. 7. 2.]


#### percentile():백분위 수

In [188]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


/var/folders/td/4qb43vgx4w92xyck7j2hlgph0000gn/T/ipykernel_44551/395359856.py:3: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
/var/folders/td/4qb43vgx4w92xyck7j2hlgph0000gn/T/ipykernel_44551/395359856.py:4: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
/var/folders/td/4qb43vgx4w92xyck7j2hlgph0000gn/T/ipykernel_44551/395359856.py:5: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additiona

#### any() : 하나의 element 이상이 True이면 True

In [191]:
a2 = np.array([[False,False,False],
               [False,True,True],
               [False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all(): 모든 element가 true여야 true

In [193]:
a2 = np.array([[False,False,True],
               [True,True,True],
               [False,True,True]])
print(a2)
print(np.all(a2))
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교연산(Comparison Operators)

In [199]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5) ## arrray에 대한 True/False 결과값 리턴
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [201]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis = 0))
print(np.any(a2 > 5, axis = 1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis = 0))
print(np.all(a2 > 5, axis = 1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [202]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1)) #배열 두개가(z*1e+02)%내외로 가까우면 True,아니면 False


[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [208]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


### 불리언 연산자(Boolean Operators)

In [212]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)]) #boolean indexing

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)]) #boolean indexing

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)]) #boolean indexing

print(~(a2 > 5))
print(a2[~(a2 > 5)]) #boolean indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [214]:
a1 = np.random.randint(1,10,10)
print(a1)
print(np.sort(a1)) # 원본 배열 정렬 반영 X
print(a1)
print(np.argsort(a1)) # 정렬되는 인덱스 위치값만 출력
print(a1)
print(a1.sort()) # 원본 배열에 정렬 반영
print(a1)

[5 3 6 3 2 6 3 4 9 2]
[2 2 3 3 3 4 5 6 6 9]
[5 3 6 3 2 6 3 4 9 2]
[4 9 1 3 6 7 0 2 5 8]
[5 3 6 3 2 6 3 4 9 2]
None
[2 2 3 3 3 4 5 6 6 9]


In [216]:
a2 = np.random.randint(1,10,(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[5 5 9]
 [2 8 1]
 [1 3 7]]
[[1 3 1]
 [2 5 7]
 [5 8 9]]
[[5 5 9]
 [1 2 8]
 [1 3 7]]


#### 부분 정렬

- partition(): 배열에서 k개의 작은 값을 반환

In [217]:
a1 = np.random.randint(1,10,10)
print(a1)
print(np.partition(a1,3))

[3 6 6 7 7 2 2 8 6 9]
[2 2 3 6 6 6 7 8 7 9]


In [221]:
a2 = np.random.randint(1,10,(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[6 3 2 7 4]
 [6 6 6 6 2]
 [5 2 1 6 9]
 [3 5 5 4 7]
 [7 5 7 2 7]]
[[3 2 4 6 7]
 [6 2 6 6 6]
 [2 1 5 6 9]
 [4 3 5 5 7]
 [2 7 5 7 7]]
[[3 2 1 4 2]
 [5 3 2 2 4]
 [6 5 5 6 7]
 [6 5 6 6 7]
 [7 6 7 7 9]]
[[3 2 4 6 7]
 [6 2 6 6 6]
 [2 1 5 6 9]
 [4 3 5 5 7]
 [2 7 5 7 7]]


# 배열 입출력

In [222]:
a2 = np.random.randint(1,10,(5,5))
print(a2)
np.save("a",a2) # Numpy 배열 객체 1개를 파일에 저장 (바이너리 파일)

[[2 9 4 6 8]
 [6 6 9 7 2]
 [2 8 8 7 8]
 [2 1 4 1 3]
 [8 8 3 8 6]]


In [223]:
!ls

Numpy_1.ipynb    a.npy            numpy-100-master


In [225]:
b2 = np.random.randint(1,10,(5,5))
print(b2)
np.savez("ab",a2,b2)  # Numpy 배열 객체 2개를 파일에 저장 (바이너리 파일)

[[9 6 6 7 1]
 [4 5 5 6 2]
 [1 7 6 1 1]
 [4 1 8 1 8]
 [4 2 2 7 7]]


In [226]:
!ls

Numpy_1.ipynb    a.npy            ab.npz           numpy-100-master


In [227]:
npy = np.load("a.npy")
print(npy)

[[2 9 4 6 8]
 [6 6 9 7 2]
 [2 8 8 7 8]
 [2 1 4 1 3]
 [8 8 3 8 6]]


In [229]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[2 9 4 6 8]
 [6 6 9 7 2]
 [2 8 8 7 8]
 [2 1 4 1 3]
 [8 8 3 8 6]]
[[9 6 6 7 1]
 [4 5 5 6 2]
 [1 7 6 1 1]
 [4 1 8 1 8]
 [4 2 2 7 7]]


In [230]:
print(a2)
np.savetxt("a.csv",a2,delimiter=',') #텍스트 파일 형태로 저장

[[2 9 4 6 8]
 [6 6 9 7 2]
 [2 8 8 7 8]
 [2 1 4 1 3]
 [8 8 3 8 6]]


In [231]:
!ls

Numpy_1.ipynb    a.npy            numpy-100-master
a.csv            ab.npz


In [232]:
!cat a.csv

2.000000000000000000e+00,9.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00
6.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00,2.000000000000000000e+00
2.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00
2.000000000000000000e+00,1.000000000000000000e+00,4.000000000000000000e+00,1.000000000000000000e+00,3.000000000000000000e+00
8.000000000000000000e+00,8.000000000000000000e+00,3.000000000000000000e+00,8.000000000000000000e+00,6.000000000000000000e+00


In [236]:
csv = np.loadtxt("a.csv", delimiter=',') #delimiter를 정의해줘야함
print(csv)

[[2. 9. 4. 6. 8.]
 [6. 6. 9. 7. 2.]
 [2. 8. 8. 7. 8.]
 [2. 1. 4. 1. 3.]
 [8. 8. 3. 8. 6.]]


In [237]:
print(b2)
np.savetxt("b.csv",b2,delimiter=',',fmt='%.2e',header = 'c1, c2, c3, c4, c5')

[[9 6 6 7 1]
 [4 5 5 6 2]
 [1 7 6 1 1]
 [4 1 8 1 8]
 [4 2 2 7 7]]


In [238]:
!cat b.csv

# c1, c2, c3, c4, c5
9.00e+00,6.00e+00,6.00e+00,7.00e+00,1.00e+00
4.00e+00,5.00e+00,5.00e+00,6.00e+00,2.00e+00
1.00e+00,7.00e+00,6.00e+00,1.00e+00,1.00e+00
4.00e+00,1.00e+00,8.00e+00,1.00e+00,8.00e+00
4.00e+00,2.00e+00,2.00e+00,7.00e+00,7.00e+00


In [239]:
csv = np.loadtxt("b.csv",delimiter=',')
print(csv)

[[9. 6. 6. 7. 1.]
 [4. 5. 5. 6. 2.]
 [1. 7. 6. 1. 1.]
 [4. 1. 8. 1. 8.]
 [4. 2. 2. 7. 7.]]
